### ISSUE TITLE
systemd: failed to build on CentOS release 6.9: error: gcrypt.h: No such file or directory

### ISSUE THREAD

**Issue by ghost** [Linuxbrew/brew#710]
I am not able to build systemd with LinuxBrew. I get the error: 
src/shared/gcrypt-util.c:23:20: fatal error: gcrypt.h: No such file or directory
compilation terminated.

[gist with debug information, output from brew --config, brew doctor, etc: error building systemd](https://gist.github.com/hqax/57a59e73cfdd9de7c38eaf71acf1d2ce)

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
`gcrypt.h` is provided by `libgcrypt`. Perhaps it should be a dependency of `systemd`.

**Comment by sjackman** [comment]
Consider installing Linuxbrew in `/home/linuxbrew/.linuxbrew/` if possible so that you can use precompiled binary packages (known as bottles) for non-relocatable formula like `systemd`.
Another possible workaround for you is `brew install --force-bottle systemd`, but no promises.

If it's an option for you, you could open a ticket with your information systems department to ask that they create a `linuxbrew` role account with home directory `/home/linuxbrew`.

The precompiled binary bottles of non-relocatable bottles can only be used if you install in `/home/linuxbrew/.linuxbrew`, otherwise they have to be built from source. See the documentation below. On macOS the default installation directory is `/usr/local`. On Linux the default installation directory is `/home/linuxbrew/.linuxbrew`.

+ http://docs.brew.sh/Installation.html#alternative-installs
+ http://docs.brew.sh/FAQ.html#why-do-you-compile-everything
+ http://docs.brew.sh/Bottles.html#cellar-cellar

**Comment by sjackman** [comment]
This issue was moved to Linuxbrew/homebrew-core#7759
