### ISSUE TITLE
epstool failed to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by renozao** [Linuxbrew/brew#175]
https://gist.github.com/8395d09deff3b735cfe9c301f806276d

**Comment by sjackman** [comment]
```
/usr/bin/gcc-5 -I./src -I./epsobj -Os -w -pipe -march=native -DX11 -DUNIX -DNONAG  -Wall -Wstrict-prototypes -Wmissing-declarations -Wmissing-prototypes -fno-builtin -fno-common -Wcast-qual -Wwrite-strings  -g      -o ./epsobj/cdoc.o -c ./src/cdoc.c
In file included from /usr/include/fcntl.h:289:0,
                 from ./src/epstool.c:41:
In function ‘open’,
    inlined from ‘exec_program.constprop’ at ./src/epstool.c:2827:13:
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:4: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
```
https://gist.github.com/anonymous/8395d09deff3b735cfe9c301f806276d#file-01-make-L23

**Comment by sjackman** [comment]
Please report build failures of particular formula to https://github.com/Linuxbrew/homebrew-core
This bug report is a duplicate of https://github.com/Linuxbrew/homebrew-core/pull/999
