### ISSUE TITLE
imake failed to build on Ubuntu 12.04.5 LTS

### ISSUE THREAD

**Issue by bw-yuhogg** [Linuxbrew/brew#52]
_From @ryants on May 25, 2016 17:7_

I get the following output when attempting to install imake (an octave dependency):
`Error: undefined method `/' for nil:NilClass`

[Gist Log](https://gist.github.com/anonymous/c65271985b2e85ab3a6fbc84cc2fd6ad)

_Copied from original issue: Linuxbrew/homebrew-core#349_

**Comment by bw-yuhogg** [comment]
Reproducible on my 14.04 machine as well.

> /home/bob/.linuxbrew/Library/Homebrew/os/mac/xquartz.rb:130:in `include'
> /home/bob/.linuxbrew/Library/Taps/homebrew/homebrew-x11/imake.rb:44:in`block in install'

The line it's complaining about is

``` ruby
      # Fix for different X11 locations.
      inreplace "X11.rules", "define TopXInclude    /**/",
                "define TopXInclude -I#{MacOS::X11.include}"
```

**Comment by bw-yuhogg** [comment]
This is a regression caused by my addition of the X11 requirement. I'll try to get this fixed as soon as I can.

**Comment by bw-yuhogg** [comment]
@ryants, this should be fixed now. Can you please do a `brew update` and try building again? Thanks!

**Comment by ryants** [comment]
imake installs perfectly, thanks!
